config/routes.rb
AwesomeApp::Application.routes.draw do
  resources :assistants

end

app/models/assistant.rb
class Assistant < ActiveRecord::Base

#Assistant.validates_presence_of(:name)
#validates_presence_of "name"

validates_presence_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assistants_controller.rb
class AssistantsController < ApplicationController
  # GET /assistants
  # GET /assistants.json
  def index
    @assistants = Assistant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assistants }
    end
  end

  # GET /assistants/1
  # GET /assistants/1.json
  def show
    @assistant = Assistant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assistant }
    end
  end

  # GET /assistants/new
  # GET /assistants/new.json
  def new
    @assistant = Assistant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assistant }
    end
  end

  # GET /assistants/1/edit
  def edit
    @assistant = Assistant.find(params[:id])
  end

  # POST /assistants
  # POST /assistants.json
  def create
    @assistant = Assistant.new(params[:assistant])

    respond_to do |format|
      if @assistant.save
        format.html { redirect_to @assistant, notice: 'Assistant was successfully created.' }
        format.json { render json: @assistant, status: :created, location: @assistant }
      else
        format.html { render action: "new" }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assistants/1
  # PUT /assistants/1.json
  def update
    @assistant = Assistant.find(params[:id])

    respond_to do |format|
      if @assistant.update_attributes(params[:assistant])
        format.html { redirect_to @assistant, notice: 'Assistant was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistants/1
  # DELETE /assistants/1.json
  def destroy
    @assistant = Assistant.find(params[:id])
    @assistant.destroy

    respond_to do |format|
      format.html { redirect_to assistants_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistants_helper.rb
module AssistantsHelper
end

app/views/assistants/_form.html.erb
<%= form_for(@assistant) do |f| %>
  <% if @assistant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assistant.errors.count, "error") %> prohibited this assistant from being saved:</h2>

      <ul>
      <% @assistant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :twitter_username %><br />
    <%= f.text_field :twitter_username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assistants/edit.html.erb
<h1>Editing assistant</h1>

<%= render 'form' %>

<%= link_to 'Show', @assistant %> |
<%= link_to 'Back', assistants_path %>

app/views/assistants/index.html.erb
<h1>Listing assistants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Twitter username</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assistants.each do |assistant| %>
  <tr>
    <td><%= assistant.name %></td>
    <td><%= assistant.twitter_username %></td>
    <td><%= link_to 'Show', assistant %></td>
    <td><%= link_to 'Edit', edit_assistant_path(assistant) %></td>
    <td><%= link_to 'Destroy', assistant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assistant', new_assistant_path %>

app/views/assistants/new.html.erb
<h1>New assistant</h1>

<%= render 'form' %>

<%= link_to 'Back', assistants_path %>

app/views/assistants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @assistant.name %>
</p>

<p>
  <b>Twitter username:</b>
  <%= @assistant.twitter_username %>
</p>


<%= link_to 'Edit', edit_assistant_path(@assistant) %> |
<%= link_to 'Back', assistants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>